services:
    adminer:
        image: adminer
        ports:
            - 8081:8080
        networks:
            - sail
        depends_on:
            - mysql
    redis:
      image: 'redis:alpine'
      ports:
        - '${REDIS_PORT:-6379}:6379'
      networks:
        - sail
      healthcheck:
        test:
          - CMD
          - redis-cli
          - ping
        retries: 3
        timeout: 5s
